# Generated by Django 3.0.5 on 2021-02-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='capital',
            field=models.BooleanField(default=False),
        ),
    ]
