version: '3.5'

services:

  sidia_db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sidia
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker-sock:/var/run/docker.sock
      - portainer-data:/data

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  portainer-data:
  postgres-data: